2025-04-28 12:20:57,406 - INFO - [<module>] - Logging configured. Log file: Selenium-Logs\app_20250428_122057.log
2025-04-28 12:20:57,406 - INFO - [<module>] - Configuration loaded.
2025-04-28 12:20:57,407 - INFO - [<module>] - Utility functions defined.
2025-04-28 12:20:57,409 - INFO - [<module>] - Flask application initialized.
2025-04-28 12:20:57,409 - INFO - [<module>] - Global state variables initialized.
2025-04-28 12:20:57,503 - INFO - [<module>] - Async Telegram API functions defined.
2025-04-28 12:20:58,003 - INFO - [<module>] - Flask async routes defined.
2025-04-28 12:20:58,007 - INFO - [info] - Running on http://0.0.0.0:5000 (CTRL + C to quit)
2025-04-28 12:21:01,386 - INFO - [index] - Serving index page.
2025-04-28 12:21:07,012 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:21:07,015 - INFO - [initiate_upload] - [1f82c492-0c35-4a39-bd40-9d5de5345e69] Saving temporary file for 'requirements.txt' to 'uploads_temp\1f82c492-0c35-4a39-bd40-9d5de5345e69_upload.tmp'
2025-04-28 12:21:07,026 - INFO - [initiate_upload] - [1f82c492-0c35-4a39-bd40-9d5de5345e69] Temporary file saved successfully for 'requirements.txt'.
2025-04-28 12:21:07,040 - INFO - [stream_progress] - SSE connection request for upload_id: 1f82c492-0c35-4a39-bd40-9d5de5345e69
2025-04-28 12:21:07,043 - ERROR - [log_exception] - Exception on /stream-progress/1f82c492-0c35-4a39-bd40-9d5de5345e69 [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
